server:
  port: 2020
spring:  h2:    console:      enabled: true
      path: /h2-console
  datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    properties:      hibernate:
        format_sql: true
  mvc:    view:      prefix: /WEB-INF/jsps/
      suffix: .jsp